name: Development Pipeline

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'


jobs:
  tests:
    uses: denis-lissek-h2-invent/jitsi-pipeline-test/.github/workflows/task-test.yml@main