name: Task test

on: workflow_call

jobs:
  artifact:
    uses: denis-lissek-h2-invent/jitsi-pipeline-test/.github/workflows/task-artifact.yml@feature/docker_keycloak_upgrade
  test:
    needs:
      - artifact

    runs-on: ubuntu-latest
    
    # region declare_services
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    # endregion declare_services
    
    steps:
      # region mysql_start
      - name: MySQL start
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql --user=root --password=root -e "CREATE USER 'jitsiadmintest'@'localhost' IDENTIFIED  BY 'password';"
          sudo mysql --user=root --password=root -e "GRANT ALL PRIVILEGES ON jitsiadmintest.* TO 'jitsiadmintest'@'localhost';"
          sudo mysql --user=root --password=root -e "FLUSH PRIVILEGES;"
      # endregion mysql_start
      # region load_artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: jitsi-admin-test_${{github.run_number}}
      - name: Unzip Artifact
        run: unzip -qq jitsi-admin-test_${{github.run_number}}.zip -d jitsi-admin-test
      # endregion load_artifact
      # region test
      # region phpunit
      - name: Run PHP-Unit tests
        working-directory: ./jitsi-admin-test
        run: php composer.phar test
      # endregion phpunit
      # endregion test