name: Task test

on: workflow_call

jobs:

    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: denis-lissek-h2-invent/jitsi-pipeline-test/.github/workflows/task-test-artifact.yml@feature/docker_keycloak_upgrade

      - name: LS
        run: ls -lah
      # region test
      # region phpunit
      - name: Run PHP-Unit tests
        run: php composer.phar test
      # endregion phpunit
      # endregion test