name: Task test artifact

on: workflow_call

jobs:
  buildTestArtifact:
    runs-on: ubuntu-latest
    # region declare_service
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
    outputs:
      artifactName: jitsi-admin-test_${{github.run_number}}
    # endregion declare_service
    steps:
      # region git_pull
      - name: Pull current commit
        uses: actions/checkout@v3
      # endregion git_pull
      # region update_php_version
      - name: Update PHP Version and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          ini-values: date.timezone ="Europe/Berlin"
      # endregion update_php_version
      # region setup
      # region mysql_start
      - name: MySQL start
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql --user=root --password=root -e "CREATE USER 'jitsiadmintest'@'localhost' IDENTIFIED  BY 'password';"
          sudo mysql --user=root --password=root -e "GRANT ALL PRIVILEGES ON jitsiadmintest.* TO 'jitsiadmintest'@'localhost';"
          sudo mysql --user=root --password=root -e "FLUSH PRIVILEGES;"
      # endregion mysql_start
      # region composer_install
      - name: Composer Install
        run: composer install
      # endregion composer_install
      # region npm_install
      - name: NPM Install
        run: |
          npm install
          npm run build
      # endregion npm_install
      # endregion setup
      # region save_artifact
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r jitsi-admin_${{github.run_number}}.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jitsi-admin-test_${{github.run_number}}
          path: jitsi-admin-test_${{github.run_number}}.zip
      # endregion save_artifact